# Generated by Django 4.0.4 on 2022-05-22 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=25, verbose_name='Название компании')),
                ('link', models.TextField(verbose_name='Ссылка на партнера ')),
                ('reviews', models.IntegerField(verbose_name='Оценка компании')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название продукта')),
                ('company', models.CharField(max_length=25, verbose_name='Производитель')),
                ('compound', models.TextField(verbose_name='Cостав продукта')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('delivery', models.DateTimeField(max_length=30, verbose_name='Доставят к ')),
                ('price', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProducts',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название продукта')),
                ('company', models.CharField(max_length=25, verbose_name='Производитель')),
                ('compound', models.TextField(verbose_name='Cостав продукта')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('delivery', models.DateTimeField(max_length=30, verbose_name='Доставят к ')),
                ('price', models.IntegerField(verbose_name='Количество')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Продукт',
                'verbose_name_plural': 'historical Продукты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPartners',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('organization', models.CharField(max_length=25, verbose_name='Название компании')),
                ('link', models.TextField(verbose_name='Ссылка на партнера ')),
                ('reviews', models.IntegerField(verbose_name='Оценка компании')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Партнер',
                'verbose_name_plural': 'historical Партнеры',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
